# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'SLUSH' do

pod 'GoogleMaps'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'

end

target 'SLUSHTests' do

end

target 'SLUSHUITests' do

end

